default_context:
  project_name: 'Annoscope'
  project_slug: 'annoscope'
  domain_main: 'annoscope.com'
  domain_staging: 'stag.annoscope.com'
  docker_swarm_stack_name_main: 'annoscope-com'
  docker_swarm_stack_name_staging: 'stag-annoscope-com'
  secret_key: '0eb6cf90ff9953fcb9db7f355e012c2253c6b4c6ba8d991abb78744f8b21829e'
  first_superuser: 'changsin@testworks.co.kr'
  first_superuser_password: 'cancerB&E76'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.annoscope.com", "https://stag.annoscope.com", "https://annoscope.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: 'smtp-mail.outlook.com'
  smtp_user: 'changsin@testworks.co.kr'
  smtp_password: 'cancerB&E76'
  smtp_emails_from_email: 'info@annoscope.com'
  postgres_password: 'twT!P2015'
  pgadmin_default_user: 'changsin@testworks.co.kr'
  pgadmin_default_user_password: 'cancerB&E76'
  traefik_constraint_tag: 'annoscope.com'
  traefik_constraint_tag_staging: 'stag.annoscope.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:twT!P2015'
  sentry_dsn: 'https://64ca1aed21994ea5a67aee8ce566e587@o1052906.ingest.sentry.io/6036825'
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  _copy_without_render: [backend/app/app/email-templates/**]
  _template: ./
